import { Router } from 'express';
import { healthRoutes } from './health.routes';
import { authRoutes } from './auth.routes';
import { usersRoutes } from './users.routes';
import { aiRoutes } from './ai.routes';
import { workspaceRoutes } from './workspace.routes';
import { calendarApiRoutes } from './calendar.routes';
import { projectRoutes } from './project.routes';
import { knowledgeRoutes } from './knowledge.routes';
import { automationRoutes } from './automation.routes';
import { uploadRoutes } from './upload.routes';
import { notificationRoutes } from './notification.routes';
import { analyticsRoutes } from './analytics.routes';
import { settingsRoutes } from './settings.routes';
import { adminRoutes } from './admin.routes';
import { taskGoalRoutes } from './taskGoal.routes';
import { dashboardRoutes } from './dashboard.routes';
import { favoritesRoutes } from './favorites.routes';
import { HomeModule } from '../modules/home/home.module';
import { db } from '../database/client';
import { authenticate } from '../middleware/auth.middleware';

const router = Router();

router.use('/health', healthRoutes);
router.use('/home', authenticate, HomeModule.init(db));
router.use('/dashboard', dashboardRoutes);
router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/user', usersRoutes);
router.use('/ai', aiRoutes);
router.use('/workspaces', workspaceRoutes);
router.use('/calendar', calendarApiRoutes);
router.use('/workspace/calendar', calendarApiRoutes);
router.use('/projects', projectRoutes);
router.use('/knowledge', knowledgeRoutes);
router.use('/automations', automationRoutes);
router.use('/workflows', automationRoutes);
router.use('/automation/workflows', automationRoutes);
router.use('/integrations', automationRoutes);
router.use('/automation', automationRoutes);
router.use('/', taskGoalRoutes);
router.use('/uploads', uploadRoutes);
router.use('/notifications', notificationRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/settings', settingsRoutes);
router.use('/admin', adminRoutes);
router.use('/favorites', favoritesRoutes);

export const apiRoutes: Router = router;
